import pptxgen from 'pptxgenjs';
import { DocumentAnalysis } from '../../core/documents/DocumentSchemaValidator';
import { logger } from '../logger';
import * as path from 'path';
import { app } from 'electron';

export class PptxGenerator {
  static async generate(doc: DocumentAnalysis, filename: string = 'NOVA_Presentation.pptx'): Promise<string> {
    logger.info(`[PptxGenerator] Generating slides for: ${doc.title}`);
    
    const pres = new pptxgen();
    
    // Title Slide
    const slide1 = pres.addSlide();
    slide1.background = { color: '001E28' };
    slide1.addText(doc.title, { x: 1, y: 2, w: '80%', color: '00FFFF', fontSize: 44, bold: true });
    slide1.addText(doc.documentType.toUpperCase(), { x: 1, y: 3.5, w: '80%', color: 'FFFFFF', fontSize: 24 });
    slide1.addText('Generated by NOVA AI', { x: 1, y: 4.5, w: '80%', color: '888888', fontSize: 14 });

    // Executive Summary
    const slide2 = pres.addSlide();
    slide2.background = { color: '001E28' };
    slide2.addText('Executive Summary', { x: 0.5, y: 0.5, color: '00FFFF', fontSize: 32 });
    slide2.addText(doc.summary, { x: 0.5, y: 1.5, w: '90%', h: 3, color: 'FFFFFF', fontSize: 20, valign: 'top' });

    // Key Points
    if (doc.keyPoints && doc.keyPoints.length > 0) {
      const slide3 = pres.addSlide();
      slide3.background = { color: '001E28' };
      slide3.addText('Key Points', { x: 0.5, y: 0.5, color: '00FFFF', fontSize: 32 });
      slide3.addText(
        doc.keyPoints.map(kp => ({ text: kp, options: { bullet: true } })), 
        { x: 0.5, y: 1.5, w: '90%', color: 'FFFFFF', fontSize: 20 }
      );
    }

    // Save to user's Documents folder safely
    const savePath = path.join(app.getPath('documents'), filename);
    await pres.writeFile({ fileName: savePath });
    logger.info(`[PptxGenerator] Saved to ${savePath}`);
    
    return savePath;
  }
}
