import React, { useEffect, useState } from 'react';
import { ApiClient } from '../../api';
import '../../styles/components/ChatSidebar.css';

export interface ChatSession {
  id: string;
  title: string;
  category: string;
  messages: Array<{ role: 'user'|'assistant', content: string }>;
}

interface Props {
  activeSessionId: string | null;
  onSelectSession: (session: ChatSession) => void;
  onNewSession: () => void;
}

export const ChatSidebar: React.FC<Props> = ({ activeSessionId, onSelectSession, onNewSession }) => {
  const [sessions, setSessions] = useState<ChatSession[]>([]);

  const loadSessions = async () => {
    try {
      const data = await ApiClient.getChatSessions();
      setSessions(data);
    } catch (err) {
      console.error('Failed to load chat sessions', err);
    }
  };

  useEffect(() => {
    loadSessions();
    // Poll every 5s to update category titles generated by AI
    const interval = setInterval(loadSessions, 5000);
    return () => clearInterval(interval);
  }, []);

  const handleDelete = async (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    try {
      await ApiClient.deleteChatSession(id);
      loadSessions();
      if (activeSessionId === id) {
        onNewSession();
      }
    } catch (err) {
      console.error('Failed to delete session', err);
    }
  };

  // Group by category
  const categories = sessions.reduce((acc, session) => {
    const cat = session.category || 'Uncategorized';
    if (!acc[cat]) acc[cat] = [];
    acc[cat].push(session);
    return acc;
  }, {} as Record<string, ChatSession[]>);

  return (
    <div className="chat-sidebar">
      <button className="new-chat-btn" onClick={onNewSession}>
        <span>+</span> New Chat
      </button>

      {Object.entries(categories).map(([category, catSessions]) => (
        <div key={category} className="chat-category">
          <div className="chat-category-title">
            {category === 'Code' && '💻 '}
            {category === 'Research' && '🔍 '}
            {category === 'System' && '⚙️ '}
            {category === 'Casual' && '☕ '}
            {category === 'Uncategorized' && '📝 '}
            {category}
          </div>
          {catSessions.map(session => (
            <div 
              key={session.id} 
              className={`chat-session-item ${activeSessionId === session.id ? 'active' : ''}`}
              onClick={() => onSelectSession(session)}
            >
              <span className="chat-session-title">{session.title}</span>
              <button className="chat-session-delete" onClick={(e) => handleDelete(e, session.id)}>
                ✖
              </button>
            </div>
          ))}
        </div>
      ))}
    </div>
  );
};
